### ISSUE TITLE
MLDoubleSpinBox in Qt 5.12.2

### ISSUE THREAD

**Issue by pi-null-mezon** [mpaperno/maxLibQt#2]
Hello. I have found this while updating from Qt 9.1 to Qt 5.12.2

MLDoubleSpinBox has been used as delegate:
```
MLDoubleSpinBox {
                from: model.min
                to:   model.max
                stepSize: model.stepsize
                onValueChanged: model.value = value
                wrap: false
            }
```
In Qt 5.9.1 it works great as expected:
![MLDoubleSpinBox works in qt_5 9 1](https://user-images.githubusercontent.com/5991537/55890105-ccd3fb80-5bba-11e9-9881-0190f432a7d0.png)
 
But not in Qt 5.12.2 (same model as in the above example): 
![MLDoubleSpinBox issue in qt_5 12 2](https://user-images.githubusercontent.com/5991537/55889131-44089000-5bb9-11e9-80f0-4ab6b73ae5d9.png)

**OS: Win7x64**
**Compiler: Mingw5.3x86 for Qt5.9.1 and Mingw7.3x86 for Qt5.12.2**

Thank you for the code sharing! 
---

**Comment by mpaperno** [comment]
Strange! Thanks for letting me know. 

What are the actual values for age/height/weight in this example?  Trying to reproduce here.

**Comment by mpaperno** [comment]
Can't seem to reproduce this. Though I haven't tried the MinGW version specifically, but did try VC2015 and GCC 7.3 (on Linux). 

Could you try it with the included `tests.qml` page and see what happens? (It can just be run in `qmlscene`.)  And/or post a simple QML example which shows the problem?

(Also not clear from your code snippet how you're setting the value of the spinbox. I assume externally somehow.)

Thanks!

```qml
        MLDoubleSpinBox {
            wrap: false;
            value: 45
		}

        MLDoubleSpinBox {
            wrap: false;
            value: 160
            to: 200
		}

        MLDoubleSpinBox {
            wrap: false;
            value: 60
		}
```

![image](https://user-images.githubusercontent.com/1366615/55923190-622eba00-5bd2-11e9-8c75-1329057e520a.png)

**Comment by pi-null-mezon** [comment]
Looks like problem arise when fractional part is omitted (Default's value is 1)
![test](https://user-images.githubusercontent.com/5991537/55936753-d9e6fe00-5c3f-11e9-8b70-79fccb974566.png)

**Comment by mpaperno** [comment]
Looks like a bug in Qt 5.12.2 specifically (tested MSVC2017 and MinGW 7.3, both x86). I worked around it in 65acc4b so it should be fixed now, and still fine for older versions. (Turned out I was testing with 5.12.1 earlier... whoops!)

Thanks again for reporting this! Looks like a possibly nasty Qt issue in general, so it's good to know about.

Guess I'm off to submit a Qt bug report... :roll_eyes:   Unless I'm missing something, but the old code still works fine in a pure JavaScript environment.  https://jsfiddle.net/d2xa0esp/3/

**Comment by mpaperno** [comment]
Filed as https://bugreports.qt.io/browse/QTBUG-75121

Looks like they broke it in 5.12.2 with https://bugreports.qt.io/browse/QTBUG-73152

Changing behavior of a common function.. and in a bugfix release.... :disappointed:
