### ISSUE TITLE
MLDoubleSpinBox 

### ISSUE THREAD

**Issue by pi-null-mezon** [mpaperno/maxLibQt#3]
Hello! Оnce again) Playing around with MLDoubleSpinBox I have found that it's text field does not updates properly if you enter value out of [from - to] range more than one time.

For the instance, let's use "controls/test.qml". MLDoubleSpinbox instance with "Default" label prepared to work in range from 0 to 10. 

Step 1. Preview qmlscene 
![image](https://user-images.githubusercontent.com/5991537/56359414-315e0e80-61ea-11e9-8329-3607dc55adc4.png)

Step 2. Write, for the instance, 20 in the text field by keyboard
![image](https://user-images.githubusercontent.com/5991537/56359508-6ff3c900-61ea-11e9-8b9b-6a5ca850fc60.png)

Step 3. Press 'Enter', value adjusted to top limit - it is ok, as expected
![image](https://user-images.githubusercontent.com/5991537/56359514-74b87d00-61ea-11e9-888d-2db32e13af4f.png)

Step 4. Once again write 20, or whatever 
![image](https://user-images.githubusercontent.com/5991537/56359635-cc56e880-61ea-11e9-82ee-a676861b2c07.png)

Step 5. Press 'Enter', oops - it is not working now (
![image](https://user-images.githubusercontent.com/5991537/56359737-0fb15700-61eb-11e9-9606-5a0f286dc60d.png)

Step 6. Even if I change focus, MLDoubleSpinBox still contains 20
![image](https://user-images.githubusercontent.com/5991537/56359849-6cad0d00-61eb-11e9-876f-8fd287b945e6.png)

**My specs.: MS Windows7x64
Qt: 5.9.1, 5.12.2
Compiller: Mingw32**

**Comment by mpaperno** [comment]
Thanks, again :)   Good catch.  Problem was the displayed value not updating, even though the actual `value` would be correct (because `value` wouldn't actually change since the last auto-correction).

**Comment by pi-null-mezon** [comment]
Thanks! Cheers!
