### ISSUE TITLE
MLDoubleSpinBox

### ISSUE THREAD

**Issue by shall0pass** [mpaperno/maxLibQt#4]
Hi.  I am writing my first QML application and am running into troubles.  I am using your MLDoubleSpin box and it behaves slightly differently than the SpinBox.  I am hoping you will see my mistake if I have one.

What I have works, until I press the + or - buttons on the spinbox.  It then appears to overwrite my value and will no longer pull up the value from the c++ code.  As far as I can tell, the SpinBox which uses integers, doesn't have this behaviour.  

QML UI file
'ComboBox {
                id: comboBox1
                anchors.right: parent.right
                anchors.rightMargin: 40
                anchors.verticalCenter: parent.verticalCenter
                textRole: "key"
                valueRole: "value"
                model: ListModel {
                    ListElement {
                        key: "7/8, 50 ohm"
                        value: 1
                    }
                    ListElement {
                        key: "1 5/8, 50 ohm"
                        value: 2
                    }
                    }
                 onCurrentValueChanged: _page3.preset = currentValue
            }
.........
            MLDoubleSpinBox {
                id: spin3
                anchors.right: parent.right
                anchors.margins: 10
                decimals: 3
                from: 0
                to: 30
                value: _page3.outer
                onValueChanged: _page3.outer = value
                stepSize: 0.1
            }
'

c++ header
'class CalcP3: public QObject
{
    Q_OBJECT
    Q_PROPERTY(double outer         READ getOuter       WRITE setOuter      NOTIFY update)

.......
}'

c++ class
{
void CalcP3::setPreset(double value){
    if (value == m_preset) return;
    m_preset = value;
    switch(m_preset) {
    case 1:
        m_outer = 0.785;
        m_inner = 0.341;
        break;
    case 2:
        m_outer = 1.527;
        m_inner = 0.664;
        break;
}
emit update();
}

........
'

**Comment by mpaperno** [comment]
Hi there.  The most obvious (to me) issue in your code is the circular binding in `spin3`, where the `value` property both depends on `_page3.outer` value, and also sets the same `_page3.outer` in `onValueChanged` (I assume `_page3` is your C++ object).  I'm a little surprised if Qt doesn't warn you about that (at runtime).  I'm guessing, but probably the first time your `onValueChanged` fires, the `spint3.value` binding to `_page3` is broken.  I'm not sure why the stock SpinBox would act differently, but OTOH it's implemented almost entirely in C++ vs. my version which relies on a lot of QML to handle bindings.  

But this this double binding issue is fairly typical, where you want to both get a value to display from a C++ object, and also save any changes back to the object.  I usually deal with this by not using an automatic binding on the control's value and setting that value the "old fashioned" way, by listening to `update()` signal from your object and then setting the control's value manually. That way the automatic bindings don't break.  I think Qt6 is supposed to deal with this issue better somehow.  The auto bindings are great when they work, but like anything automated, it's annoying when it breaks and you don't know why.

HTH,
-Max
